
You've made some plots you can be proud of, so let's learn to save them so we can cherish them forever. There's a function called `ggsave` to do just that. How do we `ggsave` our plots? 

__Let's try `help(ggsave)` or `?ggsave`.__

```{r ggsave, eval = F, echo = T}
# Get help
help(ggsave)
?ggsave

# Run the R code for your favorite plot first
ggplot(data, aes()) +
   .... +
   ....


# Then save your plot to a png file of your choosing
ggsave("results/plot_name.png")
```

<br>

<div class="note">
### <i class="fas fa-hand-spock"></i> Spock-tip! {-}

Sometimes you may want to make a plot and save it for later. For that, you give your plot a name. Any name will do.

```{r ggsave-objects, eval = F, echo = T}
# Name the ggplot you want to save
my_plot <- ggplot(...) + geom_point(...)
  
# Save it
ggsave(filename = "results/Save_it_here.png", 
       plot = my_plot)
```
</div>

<br>

_Learn more about saving plots:_ [http://stat545.com/](http://stat545.com/block017_write-figure-to-file.html)

<br>
