---
title: 'Back in a few...'
subtitle: ''
date: '2018-12-08'
summary: ''
showDate: false
showAuthor: false
slug: 'timer7'
categories: [training]
tags: 
type: ''
image: '' 
imageWidth: '27%'
imageFloat: 'left'
enableEmoji: true
---

<div style="margin-top: -30px;"></div>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=F, message=F)
```


<style>
.countdown {
  position: relative;
  width: 80%;
}

body {
  background-color: #0e0d0eeb; /*#f5f5f5 #222d32 */
}

</style>
    
<br>   


<div style="margin-left: auto; margin-right: auto;">

<iframe width="100%" height="400" src="https://www.youtube.com/embed/pT9_HJr-nso?&autoplay=1&mute=1" title="YouTube video player" frameborder="0" allowfullscreen data-external='1'></iframe>


```{r}
library(countdown)

# Get the solarized color palette
#solarized <- xaringanthemer::style_solarized_light

countdown(
  minutes = 7, 
  update_every = 5,
  start_immediately = T,
  # Fanfare when it's over
  play_sound = TRUE,
  top = "12px",
  right = "auto",
  margin = "auto",
  font_size = "9em",
  # Set timer theme to match solarized colors
  color_border              = "#0D9188FF",
  color_text                = "#073642",
  color_running_background  = "#2aa198",
  color_running_text        = "#073642",
  color_finished_background = "#e53256",
  color_finished_text       = "white"
)
```

</div>

</br>