
<details>
<summary class="btn_code_blue">
<span style="color: #f6cd00;"><i class="fas fa-star"></i>__BONUS__<i class="fas fa-star"></i> </span> __Does the order of arguments matter?__ 
</summary>

<div class="note" style="margin-top: -14px;">
<p>

Let's say you had a function called **`feed_porgs()`**, which has 3 arguments:

- `feed_porgs(breakfast = "fish", lunch = "veggies", dinner = "clams")`.

A shorthand to write this would be:

- `feed_porgs("fish", "veggies", "clams")`. 

This works out just fine because all of the arguments were entered in the default order, the same as above.

<br>

#### What happens if we write: {-}

- `feed_porgs("veggies", "clams", "fish")`

Now the function sends _veggies_ to the porgs for breakfast because that is the first argument. 

Unfortunately, that's no good for the porgs. So if we really want to write _"veggies"_ first, we'll need to tell R which food item belongs to which meal. 

#### Like this: {-}

- `feed_porgs(lunch = "veggies", breakfast = "fish", dinner = "clams")`.

<br>

#### What about `read_csv()`? {-}

For `read_csv` we wrote:

- `read_csv(scrap_file, column_names, skip = 1)`

R assumes that the first argument (the data file) is `scrap_file` and that the 2nd argument "col_names" should be set to `column_names`. Next, the `skip =` argument is included explicitly because _skip_ is the __10th__ argument in `read_csv()`. 

If we don't include `skip=`, R will assume the value `1` is meant for the function's __3rd__ argument. 

</p></div></details>

<br>
