
It's time for some Earth data. Use your new R skills to explore some data from closer to home.


## 0. Set up your project {-}

- Open a new project
- Open a new R script
- Create a `data` folder in your project directory 
- Copy your data to that folder


## Begin your analysis {-}

## 1. Read data into R {-}
```{r, eval=F}
library(readr)
library(janitor)

# Read a CSV file
air_data <- read_csv("data/My-data.csv")


# Have an EXCEL file?
## You can use read_excel() from the readxl package
install.packages(readxl)

library(readxl)

# Read an EXCEL file
air_data <- read_excel("data/My-data.xlsx")
```


## 2. Clean the column names {-}
```{r, eval=F}
air_data <- clean_names(air_data)
```


## 3. Get to know your data {-}

>
> Hint: `summary()`, `glimpse()`, `nrow()`, `names()`
>


## 4. Plot the data {-}
```{r, eval=F}
library(ggplot2)

# Remember the ggplot sandwich!
ggplot(air_data, aes(x = TEMP_F, y = OZONE)) +
    geom_point(aes(color = site_name))
```


>
> Keep exploring...
>

<br>
