
<details>
<summary class="btn_code_blue">
<span style="color: #f6cd00;"><i class="fas fa-star"></i></span> __Does the order of arguments matter?__ 
</summary>

<div class="note" style="margin-top: -14px;">
<p>

#### It depends. {-}

Let's say you had a function called **`feed_porgs()`** that takes 3 arguments: breakfast, lunch, and dinner.

- `feed_porgs(breakfast = "donut", lunch = "veggies", dinner = "clams")`.

A shorthand to write this would be:

- `feed_porgs("donut", "veggies", "clams")`. 

This shortcut works out just fine because all of the arguments were entered in the default order, the same as above.

<br>

#### But what happens if we write: {-}

- `feed_porgs("veggies", "clams", "donut")`

Now the function sends _veggies_ to the porgs for breakfast because that is the first argument. Yuk!

Unfortunately, that's no good for the porgs. If we really want to write _"veggies"_ first, we'll need to tell R which food item belongs to which meal. 

#### Like this: {-}

- `feed_porgs(lunch = "veggies", breakfast = "fish", dinner = "clams")`.

<br>

#### What about `read_csv()`? {-}

When we ran *read_csv* we wrote:

- `read_csv("https://mn-r.netlify.com/data/starwars_scrap_jakku.csv")`


R assumes that the first argument you supplied is meant to be the path to the data file. That's because _file_ is the __1st__ argument in `read_csv()`.

Howerver, if we wanted to tell the function to skip the first row in the file, we would need to add `skip = 1`, because skip by default is the 10th argument in the function. 

So we would add skip like this:

```{r, eval=F}
read_csv("https://mn-r.netlify.com/data/starwars_scrap_jakku.csv", skip = 1)
```

</p></div></details>

