

## Total pounds per shipment {-}
<hr class="hrlvl2">

Let's `mutate()`! 

Now that we have pounds per unit we can use `mutate` to calculate the total pounds for each shipment.


```{r, echo=F, eval=F}
scrap <- scrap %>% 
         mutate(total_pounds = amount * pounds_per_unit)
```

__Fill in the blank__
```{r, eval=F}

scrap <- scrap %>% 
         mutate(total_pounds = amount *  _____________ )
```

<details>
<summary class = "btn_code">_Show code_</summary>
<p><div class="quiz" style="margin-top: -6px;">
```{r, eval=F}
scrap <- scrap %>% 
         mutate(total_pounds = amount * pounds_per_unit)
```
</div></p></details>


## Total price per shipment {-}

<div class="tip">
### <i class="fa fa-user-astronaut" style="color: green;"></i> Explore! {-}

```{r exer-tabs, results='asis', echo=F}
source("../../insert_tabs.R")

tabs <- c("Total price", "Show hint", "Show code")

content <- c(Exercise = "<h4> Total price </h4>

We need to do some serious multiplication. We now have the total amount shipped in pounds, and the price per pound, but we want to know the total price for each transaction. 

How do we calculate that? 

code_start
# Calculate the total price for each shipment
scrap <- scrap %>% 
         mutate(credits = ________ * ________ )
         
code_end",

show_hint = '<h4> Total price </h4>

We need to do some serious multiplication. We now have the total amount shipped in pounds, and the price per pound, but we want to know the total price for each transaction. 

How do we calculate that?

code_start
# Calculate the total price for each shipment
scrap <- scrap %>% 
         mutate(credits = total_pounds  * ________ )

code_end',

show_code = '<h4> Total price </h4>

We need to do some serious multiplication. We now have the total amount shipped in pounds, and the price per pound, but we want to know the total price for each transaction. 

How do we calculate that?

code_start
# Calculate the total price for each shipment
scrap <- scrap %>% 
         mutate(credits = total_pounds * price_per_pound)
         
code_end')

tab_html <- add_tabs(tabs, content)

cat(paste0(tab_html, collapse = "\n"))
```
</div>

<br>

```{r, echo=F, eval=F}
# Calculate the total price for each shipment
scrap <- scrap %>% 
         mutate(credits = total_pounds * price_per_pound)
```


## Price per item {-}

__Great!__ Let's add one last column. We can divide the shipment's _credits_ by the _amount_ of items to get the `price_per_unit`.

```{r, eval=F}
# Calculate the price per unit
scrap <- scrap %>% 
         mutate(price_per_unit = credits / amount)
```

<br>
