---
title: "Why R?"
self_contained: false
output: 
  xaringan::moon_reader:
    self_contained: false
    lib_dir: libs
    chakra: libs/remark-latest.min.js
    #css: css/camp_style.css
    seal: false
    #fontsize: 18pt
    #monofont: Source Code Pro
    includes: 
      in_header: header.html
    nature:
      slideNumberFormat: ""
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include=FALSE}
library(rmarkdown)
library(knitr)
library(magrittr)

xaringanExtra::use_clipboard()

opts_chunk$set(error=TRUE, color=NULL, message=FALSE, eval=T)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())

#mod_url <- "https://raw.githubusercontent.com/MPCA-air/r-modules/master/modules/"
#source("https://raw.githubusercontent.com/MPCA-air/r-modules/master/R/hook_add_color.R")
#source("https://raw.githubusercontent.com/MPCA-air/r-modules/master/R/hook_add_mod.R")
```


<div style="clear: both;"></div>

<br>


# We R growing {-}
<hr class="hr2">
```{r whyR, child='../../static/modules/intro/_whyr/mpca.Rmd'}
```


## Example R project {-}
```{r ex-ozone2, child='../../static/modules/_example_7steps/ozone.Rmd'}
```


<br>


### <i class="fa fa-rocket" aria-hidden="true"></i> Return to [Homebase](../post/day-1.html) {-}

<br>
